// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package mock_reaction is a generated GoMock package.
package mock_reaction

import (
	model "readmodels/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockControllerService is a mock of ControllerService interface.
type MockControllerService struct {
	ctrl     *gomock.Controller
	recorder *MockControllerServiceMockRecorder
}

// MockControllerServiceMockRecorder is the mock recorder for MockControllerService.
type MockControllerServiceMockRecorder struct {
	mock *MockControllerService
}

// NewMockControllerService creates a new mock instance.
func NewMockControllerService(ctrl *gomock.Controller) *MockControllerService {
	mock := &MockControllerService{ctrl: ctrl}
	mock.recorder = &MockControllerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerService) EXPECT() *MockControllerServiceMockRecorder {
	return m.recorder
}

// GetPostLikesMetadata mocks base method.
func (m *MockControllerService) GetPostLikesMetadata(postId, lastUsername string, limit int) ([]*model.UserMetadata, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikesMetadata", postId, lastUsername, limit)
	ret0, _ := ret[0].([]*model.UserMetadata)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPostLikesMetadata indicates an expected call of GetPostLikesMetadata.
func (mr *MockControllerServiceMockRecorder) GetPostLikesMetadata(postId, lastUsername, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikesMetadata", reflect.TypeOf((*MockControllerService)(nil).GetPostLikesMetadata), postId, lastUsername, limit)
}

// GetPostSuperlikesMetadata mocks base method.
func (m *MockControllerService) GetPostSuperlikesMetadata(postId, lastUsername string, limit int) ([]*model.UserMetadata, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostSuperlikesMetadata", postId, lastUsername, limit)
	ret0, _ := ret[0].([]*model.UserMetadata)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPostSuperlikesMetadata indicates an expected call of GetPostSuperlikesMetadata.
func (mr *MockControllerServiceMockRecorder) GetPostSuperlikesMetadata(postId, lastUsername, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostSuperlikesMetadata", reflect.TypeOf((*MockControllerService)(nil).GetPostSuperlikesMetadata), postId, lastUsername, limit)
}
