// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_reaction is a generated GoMock package.
package mock_reaction

import (
	model "readmodels/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreatePostLike mocks base method.
func (m *MockRepository) CreatePostLike(data *model.PostLike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostLike", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePostLike indicates an expected call of CreatePostLike.
func (mr *MockRepositoryMockRecorder) CreatePostLike(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostLike", reflect.TypeOf((*MockRepository)(nil).CreatePostLike), data)
}

// CreatePostSuperlike mocks base method.
func (m *MockRepository) CreatePostSuperlike(data *model.PostSuperlike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostSuperlike", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePostSuperlike indicates an expected call of CreatePostSuperlike.
func (mr *MockRepositoryMockRecorder) CreatePostSuperlike(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostSuperlike", reflect.TypeOf((*MockRepository)(nil).CreatePostSuperlike), data)
}

// CreateReview mocks base method.
func (m *MockRepository) CreateReview(data *model.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockRepositoryMockRecorder) CreateReview(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockRepository)(nil).CreateReview), data)
}

// DeletePostLike mocks base method.
func (m *MockRepository) DeletePostLike(data *model.PostLike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostLike", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostLike indicates an expected call of DeletePostLike.
func (mr *MockRepositoryMockRecorder) DeletePostLike(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostLike", reflect.TypeOf((*MockRepository)(nil).DeletePostLike), data)
}

// DeletePostSuperlike mocks base method.
func (m *MockRepository) DeletePostSuperlike(data *model.PostSuperlike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostSuperlike", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostSuperlike indicates an expected call of DeletePostSuperlike.
func (mr *MockRepositoryMockRecorder) DeletePostSuperlike(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostSuperlike", reflect.TypeOf((*MockRepository)(nil).DeletePostSuperlike), data)
}

// GetLikesMetadataByPostId mocks base method.
func (m *MockRepository) GetLikesMetadataByPostId(postId, lastUsername string, limit int) ([]*model.UserMetadata, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesMetadataByPostId", postId, lastUsername, limit)
	ret0, _ := ret[0].([]*model.UserMetadata)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLikesMetadataByPostId indicates an expected call of GetLikesMetadataByPostId.
func (mr *MockRepositoryMockRecorder) GetLikesMetadataByPostId(postId, lastUsername, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesMetadataByPostId", reflect.TypeOf((*MockRepository)(nil).GetLikesMetadataByPostId), postId, lastUsername, limit)
}

// GetReviewsByPostId mocks base method.
func (m *MockRepository) GetReviewsByPostId(postId string, lastReviewId uint64, limit int) ([]*model.Review, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewsByPostId", postId, lastReviewId, limit)
	ret0, _ := ret[0].([]*model.Review)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetReviewsByPostId indicates an expected call of GetReviewsByPostId.
func (mr *MockRepositoryMockRecorder) GetReviewsByPostId(postId, lastReviewId, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewsByPostId", reflect.TypeOf((*MockRepository)(nil).GetReviewsByPostId), postId, lastReviewId, limit)
}

// GetSuperlikesMetadataByPostId mocks base method.
func (m *MockRepository) GetSuperlikesMetadataByPostId(postId, lastUsername string, limit int) ([]*model.UserMetadata, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuperlikesMetadataByPostId", postId, lastUsername, limit)
	ret0, _ := ret[0].([]*model.UserMetadata)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSuperlikesMetadataByPostId indicates an expected call of GetSuperlikesMetadataByPostId.
func (mr *MockRepositoryMockRecorder) GetSuperlikesMetadataByPostId(postId, lastUsername, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuperlikesMetadataByPostId", reflect.TypeOf((*MockRepository)(nil).GetSuperlikesMetadataByPostId), postId, lastUsername, limit)
}
