// Code generated by MockGen. DO NOT EDIT.
// Source: user_unsuperliked_post_event_handler.go

// Package mock_reaction_handler is a generated GoMock package.
package mock_reaction_handler

import (
	model "readmodels/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserUnsuperlikedPostEventService is a mock of UserUnsuperlikedPostEventService interface.
type MockUserUnsuperlikedPostEventService struct {
	ctrl     *gomock.Controller
	recorder *MockUserUnsuperlikedPostEventServiceMockRecorder
}

// MockUserUnsuperlikedPostEventServiceMockRecorder is the mock recorder for MockUserUnsuperlikedPostEventService.
type MockUserUnsuperlikedPostEventServiceMockRecorder struct {
	mock *MockUserUnsuperlikedPostEventService
}

// NewMockUserUnsuperlikedPostEventService creates a new mock instance.
func NewMockUserUnsuperlikedPostEventService(ctrl *gomock.Controller) *MockUserUnsuperlikedPostEventService {
	mock := &MockUserUnsuperlikedPostEventService{ctrl: ctrl}
	mock.recorder = &MockUserUnsuperlikedPostEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUnsuperlikedPostEventService) EXPECT() *MockUserUnsuperlikedPostEventServiceMockRecorder {
	return m.recorder
}

// DeletePostSuperlike mocks base method.
func (m *MockUserUnsuperlikedPostEventService) DeletePostSuperlike(data *model.PostSuperlike) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeletePostSuperlike", data)
}

// DeletePostSuperlike indicates an expected call of DeletePostSuperlike.
func (mr *MockUserUnsuperlikedPostEventServiceMockRecorder) DeletePostSuperlike(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostSuperlike", reflect.TypeOf((*MockUserUnsuperlikedPostEventService)(nil).DeletePostSuperlike), data)
}
