// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_follow is a generated GoMock package.
package mock_follow

import (
	follow "readmodels/internal/follow"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFollowerMetadatas mocks base method.
func (m *MockRepository) GetFollowerMetadatas(followerIds []string) (*[]follow.FollowerMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowerMetadatas", followerIds)
	ret0, _ := ret[0].(*[]follow.FollowerMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowerMetadatas indicates an expected call of GetFollowerMetadatas.
func (mr *MockRepositoryMockRecorder) GetFollowerMetadatas(followerIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowerMetadatas", reflect.TypeOf((*MockRepository)(nil).GetFollowerMetadatas), followerIds)
}
