// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_follow is a generated GoMock package.
package mock_follow

import (
	follow "readmodels/internal/follow"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetFolloweesMetadata mocks base method.
func (m *MockRepository) GetFolloweesMetadata(followeeIds []string) (*[]follow.FolloweeMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolloweesMetadata", followeeIds)
	ret0, _ := ret[0].(*[]follow.FolloweeMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFolloweesMetadata indicates an expected call of GetFolloweesMetadata.
func (mr *MockRepositoryMockRecorder) GetFolloweesMetadata(followeeIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolloweesMetadata", reflect.TypeOf((*MockRepository)(nil).GetFolloweesMetadata), followeeIds)
}

// GetFollowersMetadata mocks base method.
func (m *MockRepository) GetFollowersMetadata(followerIds []string) (*[]follow.FollowerMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowersMetadata", followerIds)
	ret0, _ := ret[0].(*[]follow.FollowerMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowersMetadata indicates an expected call of GetFollowersMetadata.
func (mr *MockRepositoryMockRecorder) GetFollowersMetadata(followerIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowersMetadata", reflect.TypeOf((*MockRepository)(nil).GetFollowersMetadata), followerIds)
}
